spring:
  datasource:
    url: jdbc:h2:mem:tripdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

  messages:
    basename: messages

mybatis:
  mapper-locations: classpath*:mapper/*.xml


