spring:
  datasource:
    url: jdbc:h2:tcp://127.0.0.1/~/triple
    username: sa
    password:
    driver-class-name: org.h2.Driver

  messages:
    basename: messages

mybatis:
  mapper-locations: classpath*:mapper/*.xml


