-- 사용자
INSERT INTO TP_USER (USER_ID, USER_NAME) VALUES ('test1', 'test1');
INSERT INTO TP_USER (USER_ID, USER_NAME) VALUES ('test2', 'test2');
INSERT INTO TP_USER (USER_ID, USER_NAME) VALUES ('test3', 'test3');

--도시
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Seoul', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Busan', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Daegu', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Daejeon', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Gwangju', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Ulsan', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Jeju', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Incheon', 1);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Tokyo', 2);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Osaka', 2);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Fukuoka', 2);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Sapporo', 2);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Bangkok', 3);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Pai', 3);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Pattaya', 3);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('ChiangMai', 3);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Phuket', 3);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('NewYork', 4);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Chicago', 4);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Houston', 4);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('Boston', 4);
INSERT INTO TP_CITY (CITY_NAME, COUNTRY_ID) VALUES ('LosAngeles', 4);

